variables:
  HTTP_PROXY: http://www-proxy-hqdc.us.oracle.com:80
  HTTPS_PROXY: http://www-proxy-hqdc.us.oracle.com:80
  NO_PROXY: 127.0.0.1,localhost,*.oracle.com,*.oraclecorp.com,.oraclecloud.com
  http_proxy: http://www-proxy-hqdc.us.oracle.com:80
  https_proxy: http://www-proxy-hqdc.us.oracle.com:80
  no_proxy: 127.0.0.1,localhost,*.oracle.com,*.oraclecorp.com,*.oraclecloud.com

before_script:
  - echo $MAVEN_SETTINGS_XML > settings.xml
stages:
  - download_nvm
  - setup_node_js
  - setup_project
  - build_and_test

download_nvm:
  stage: download_nvm
  script:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
  tags:
  - coherence

setup_node_js:
  stage: setup_node_js
  script:
  - nvm install v12.6.0
  - node -v
  - npm -v
  tags:
  - coherence

setup_project:
  stage: setup_project
  script:
  - cat ./package.json
  - env
  - npm install
  - npm --only=dev install
  - npm test
  tags:
  - coherence

build_and_test:
  stage: build_and_test
  script:
  - npm test
  tags:
  - coherence
