# Copyright 2020 Oracle Corporation and/or its affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# ---------------------------------------------------------------------------
# Coherence JavaScript Client GitHub Actions CI build.
# ---------------------------------------------------------------------------

name: Node.js CI

on:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    types:
      - opened
      - committed
    branches:
    - '*'
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - run: npm install
    - run: npm run coh-up
    - run: npm run grpc
    - run: docker ps -a
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'
    - run: npm run test
    - run: npm run coh-down
